version: '3'

services:
  app:
    container_name: "app"
    build:
      context: "."
      dockerfile: "build/app/Dockerfile"
    ports:
      - "80:8080"
    tty: true
  db:
    container_name: "db"
    build:
      context: "."
      dockerfile: "build/db/Dockerfile"
    ports:
      - "5432:5432"
    volumes:
      - "./build/db/setup.sql:/docker-entrypoint-initdb.d/setup.sql"
